### PR TITLE
build: Replace deprecated function invocations

### PR DESCRIPTION
**Pull request by gkelly**
*Description of changes:*

Using `whitelist_type` and `whitelist_var` throws warnings. Replace these invocations with the `allowlist_type` and `allowlist_var` variants.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by andraprs** [comment]
The following error appears in the CI:

```
   Compiling nitro-cli v1.0.10 (/nitro_src)
error[E0599]: no method named `allowlist_type` found for struct `bindgen::Builder` in the current scope
  --> build.rs:75:10
   |
75 |         .allowlist_type("ne_.*")
   |          ^^^^^^^^^^^^^^ help: there is an associated function with a similar name: `blacklist_type`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `nitro-cli`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [.build-nitro-cli] Error 101
```

The diff for the updated version of the Cargo.lock needs to also be added to the PR.

https://github.com/aws/aws-nitro-enclaves-cli/blob/main/Cargo.lock
https://github.com/aws/aws-nitro-enclaves-cli/blob/main/Cargo.lock#L70

One option to have this file updated is by using one of the following commands in the root directory of this repo:

```
// Update to the latest available version
$ cargo update -p bindgen

// Update to a provided version
$ cargo update -p bindgen --precise <version>
```

**Comment by gkelly** [comment]
Updated the PR with `cargo update -p bindgen` and checked with `cargo build`.

**Comment by andraprs** [comment]
> Updated the PR with `cargo update -p bindgen` and checked with `cargo build`.

Alright, let's see what happens now. It's this make target - https://github.com/aws/aws-nitro-enclaves-cli/blob/main/Makefile#L255 - that returns error, given the crates have been updated.

I submitted this PR - https://github.com/aws/aws-nitro-enclaves-cli/pull/245 - for adding a Makefile target to update the THIRD_PARTY_LICENSES_RUST_CRATES.html file. Then you can include in this PR the diff for this file as well.

**Review by petreeftime — APPROVED** [review]

**Comment by gkelly** [comment]
Updated PR by running `make update-third-party-licenses-rust-crates-html`.

**Review by andraprs — APPROVED** [review]

**Review by petreeftime — APPROVED** [review]

**Pull request merged**
