### PR TITLE
Changed the RUST_VERSION to 1.49 to solve issue #220

### PR DESCRIPTION
**Pull request by dreemkiller**
*Issue #, if available:*
This is **a** fix for #220. I've no idea if is the appropriate way to solve this for the project.

*Description of changes:*
In file tools/Dockerfile1804, changed the line:
```
ENV RUST_VERSION 1.41.1
```
to:
```
ENV RUST_VERSION 1.49
```
This changes the version of rust that is compiling the code.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by petreeftime — APPROVED** [review]
It seems that this feature was included in 1.42, so a more conservative approach would be to update to that instead. I don't see a reason why not to use 1.49 if the project compiles with it though, as long as we can test that it builds with something older as well, but that would have to be part of another PR. Any other thoughts on this?

**Comment by petreeftime** [comment]
It seems that the version should be listed as `1.49.0`, otherwise it wouldn't build. Likely the container could do with a newer rustup version, but could you please list the version exactly?

**Comment by dreemkiller** [comment]
I've updated it to be specific at 1.49.0, and it does work. Again, it is up to you to decide if you actually want to upgrade your toolchain this way.

**Comment by alcioa** [comment]
Hi, the issue is that running `make nitro-format` and `make nitro-clippy` shall fail with 1.49.0 due to the Rust toolchain upgrade.

**Comment by dreemkiller** [comment]
As mentioned in the filed issue, then this may not be the way you want to move forward. The other alternative is to be more specific in the version of `cargo-audit` that you specify.

This pull request solves the problem for me. If you'd like to take the alternate approach to solving the problem, please feel free to reject this PR and solve it in the way most appropriate for the project.

**Comment by alcioa** [comment]
@dreemkiller we're closing this as #224 with this version is now in main branch.

**Pull request closed without merging**
