### PR TITLE
tools: Update cargo-about crate to the latest version

### PR DESCRIPTION
**Pull request by andraprs**
Update the cargo-about crate to v0.3.0, the latest version.

Include the generated updates for the
THIRD_PARTY_LICENSES_RUST_CRATES.html file.

Signed-off-by: Andra Paraschiv <andraprs@amazon.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by petreeftime — COMMENTED** [review]
Could we not include the THIRD_PARTY_LICENSES_RUST_CRATES file if we can build it from scratch? It adds friction when updating and it really only needed when we distribute the binaries.

**Comment by andraprs** [comment]
> Could we not include the THIRD_PARTY_LICENSES_RUST_CRATES file if we can build it from scratch? It adds friction when updating and it really only needed when we distribute the binaries.

The THIRD_PARTY_LICENSES file is present in this GitHub repo and in the nitro-cli RPM spec https://github.com/aws/aws-nitro-enclaves-cli/blob/main/SPECS/aws-nitro-enclaves-cli.spec#L14. The THIRD_PARTY_LICENSES_RUST_CRATES.html file is present in the GitHub repo and the initial commit - https://github.com/aws/aws-nitro-enclaves-cli/commit/cff1eb9a902633e468b04e9f44ab2e03cf4cacd4 - included a check in the CI to have this file updated.

**Comment by petreeftime** [comment]
> > Could we not include the THIRD_PARTY_LICENSES_RUST_CRATES file if we can build it from scratch? It adds friction when updating and it really only needed when we distribute the binaries.
> 
> The THIRD_PARTY_LICENSES file is present in this GitHub repo and in the nitro-cli RPM spec https://github.com/aws/aws-nitro-enclaves-cli/blob/main/SPECS/aws-nitro-enclaves-cli.spec#L14. The THIRD_PARTY_LICENSES_RUST_CRATES.html file is present in the GitHub repo and the initial commit - [cff1eb9](https://github.com/aws/aws-nitro-enclaves-cli/commit/cff1eb9a902633e468b04e9f44ab2e03cf4cacd4) - included a check in the CI to have this file updated.

Sure, but the THIRD_PARTY_LICENSES file is generated by some other means and the binery files it talks about are actually distributed with the repository as well. The THIRD_PARTY_LICENSES_RUST_CRATES is written by this tool instead, and we distribute the binaries of aws-nitro-enclaves-cli only as part of the RPM, which is the only point where they are really relevant.

**Comment by andraprs** [comment]
> > > Could we not include the THIRD_PARTY_LICENSES_RUST_CRATES file if we can build it from scratch? It adds friction when updating and it really only needed when we distribute the binaries.
> > 
> > 
> > The THIRD_PARTY_LICENSES file is present in this GitHub repo and in the nitro-cli RPM spec https://github.com/aws/aws-nitro-enclaves-cli/blob/main/SPECS/aws-nitro-enclaves-cli.spec#L14. The THIRD_PARTY_LICENSES_RUST_CRATES.html file is present in the GitHub repo and the initial commit - [cff1eb9](https://github.com/aws/aws-nitro-enclaves-cli/commit/cff1eb9a902633e468b04e9f44ab2e03cf4cacd4) - included a check in the CI to have this file updated.
> 
> Sure, but the THIRD_PARTY_LICENSES file is generated by some other means and the binry files it talks about are actually distributed with the repository as well. The THIRD_PARTY_LICENSES_RUST_CRATES is written by this tool instead, and we distribute the binary of aws-nitro-enclaves-cli only as part of the RPM, which is the only point where this file is really relevant.

When would the THIRD_PARTY_LICENSES_RUST_CRATES file be generated? In which workflow logic would this be included e.g. steps from the RPM spec, during RPM build, which steps in this file generation would need access to network and which not?

**Review by petreeftime — APPROVED** [review]

**Review by lexnv — APPROVED** [review]

**Pull request merged**
